### PR TITLE
Initial Chinese Translation

### PR DESCRIPTION
**Pull request by HanCFCat**

### CODE REVIEW

**Comment by starry69** [comment]
Hi! Thanks for the PR, can you please rename `values-zh-cn` folder with `values-zh-rCN`?

**Comment by starry69** [comment]
Actually nevermind, I'll correct it after merging. Thanks again!

**Comment by HanCFCat** [comment]
Yeah,thanks,will modify it.

**Comment by TheHitMan7** [comment]
> Yeah,thanks,will modify it.

You don't have to modify anything.

**Pull request merged**
